In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [5]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [9]:
df.dropna(how='any', inplace=True)

In [10]:
len(df)

7032

In [11]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [12]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [13]:
X=df.drop(['customerID', 'Churn'], axis=1)

In [14]:
y=df.Churn.values

In [15]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50

In [16]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [17]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [18]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding

X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [19]:
X.head(1)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [20]:
# Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [21]:
len(X_train)

5274

In [22]:
len(X_test)

1758

In [23]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [24]:
X_train_sc

array([[-0.44476923,  0.92188276,  1.30280911, ..., -0.52101451,
         1.39630385, -0.54565211],
       [ 2.24835697, -1.16295693,  0.17238453, ..., -0.52101451,
         1.39630385, -0.54565211],
       [-0.44476923,  1.49419169, -0.37867664, ...,  1.91933233,
        -0.7161765 , -0.54565211],
       ...,
       [-0.44476923, -0.79504404, -1.50743637, ..., -0.52101451,
        -0.7161765 ,  1.83266955],
       [-0.44476923,  1.04452039,  0.92655586, ..., -0.52101451,
         1.39630385, -0.54565211],
       [ 2.24835697, -0.79504404,  1.05974285, ..., -0.52101451,
         1.39630385, -0.54565211]])

In [25]:
X_test_sc

array([[-0.44476923, -1.28559456, -0.38367115, ..., -0.52101451,
        -0.7161765 ,  1.83266955],
       [-0.44476923,  0.43133224, -0.28877542, ..., -0.52101451,
        -0.7161765 ,  1.83266955],
       [-0.44476923,  0.63572829,  1.29282009, ..., -0.52101451,
         1.39630385, -0.54565211],
       ...,
       [-0.44476923,  1.00364118,  0.98815485, ..., -0.52101451,
         1.39630385, -0.54565211],
       [-0.44476923,  0.10429857,  1.17295179, ..., -0.52101451,
         1.39630385, -0.54565211],
       [-0.44476923, -1.24471535, -1.52075507, ..., -0.52101451,
        -0.7161765 ,  1.83266955]])

#### kNN Classifier

In [26]:
# Call the kNN Classifier
from sklearn.neighbors import KNeighborsClassifier

# Initiating the classifier
model = KNeighborsClassifier()

# Passing the data to classifier
model.fit(X_train_sc, y_train)

KNeighborsClassifier()

In [27]:
y_pred = model.predict(X_test_sc)

In [28]:
y_pred

array(['Yes', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [29]:
y_test

array(['Yes', 'No', 'No', ..., 'No', 'Yes', 'No'], dtype=object)

In [30]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred)*100)

76.67804323094425

#### New data prediction

In [31]:
X_test_sc

array([[-0.44476923, -1.28559456, -0.38367115, ..., -0.52101451,
        -0.7161765 ,  1.83266955],
       [-0.44476923,  0.43133224, -0.28877542, ..., -0.52101451,
        -0.7161765 ,  1.83266955],
       [-0.44476923,  0.63572829,  1.29282009, ..., -0.52101451,
         1.39630385, -0.54565211],
       ...,
       [-0.44476923,  1.00364118,  0.98815485, ..., -0.52101451,
         1.39630385, -0.54565211],
       [-0.44476923,  0.10429857,  1.17295179, ..., -0.52101451,
         1.39630385, -0.54565211],
       [-0.44476923, -1.24471535, -1.52075507, ..., -0.52101451,
        -0.7161765 ,  1.83266955]])

In [32]:
X_test.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [33]:
data = [[0, 2, 87, 178, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1]]

In [34]:
data_sc = sc.transform(data)

single = model.predict(data_sc)

print(single)

['Yes']

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [35]:
data_sc = sc.transform(data)

single = model.predict_proba(data_sc)

print(single)

[[0.2 0.8]]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

#### Decision Tree Classifier

In [36]:
# Call the DT Classifier
from sklearn.tree import DecisionTreeClassifier

# Initiating the classifier
model_dt = DecisionTreeClassifier()

# Passing the data to classifier
model_dt.fit(X_train_sc, y_train)

DecisionTreeClassifier()

In [37]:
y_pred_dt = model_dt.predict(X_test_sc)

In [38]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_dt)*100)

72.9806598407281

#### Random Forest Classifier

In [39]:
# Call the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Initiating the classifier
model_rf = RandomForestClassifier(n_estimators=200)

# Passing the data to classifier
model_rf.fit(X_train_sc, y_train)

RandomForestClassifier(n_estimators=200)

In [40]:
y_pred_rf = model_rf.predict(X_test_sc)

In [41]:
# Classification metrics = to check how the model is behaving

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_rf)*100)

79.23777019340159

In [42]:
from sklearn.metrics import classification_report

knn_report = classification_report(y_test, y_pred)
dt_report = classification_report(y_test, y_pred_dt)
rf_report = classification_report(y_test, y_pred_rf)

In [43]:
print('knn report', knn_report)

knn report               precision    recall  f1-score   support

          No       0.83      0.86      0.84      1285
         Yes       0.58      0.50      0.54       473

    accuracy                           0.77      1758
   macro avg       0.70      0.68      0.69      1758
weighted avg       0.76      0.77      0.76      1758

In [44]:
print('dt report', dt_report)

dt report               precision    recall  f1-score   support

          No       0.81      0.82      0.82      1285
         Yes       0.50      0.48      0.49       473

    accuracy                           0.73      1758
   macro avg       0.65      0.65      0.65      1758
weighted avg       0.73      0.73      0.73      1758

In [45]:
print('rf report', rf_report)

rf report               precision    recall  f1-score   support

          No       0.82      0.91      0.87      1285
         Yes       0.66      0.47      0.55       473

    accuracy                           0.79      1758
   macro avg       0.74      0.69      0.71      1758
weighted avg       0.78      0.79      0.78      1758

#### Naive Bayes Classifier

In [46]:
# Call the Random Forest Classifier
from sklearn.naive_bayes import BernoulliNB

# Initiating the classifier
model_nb = BernoulliNB()

# Passing the data to classifier
model_nb.fit(X_train_sc, y_train)

# Predictions
y_pred_nb = model_nb.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_nb)*100)

72.86689419795222

#### SVM Classifier

In [47]:
# Call the Random Forest Classifier
from sklearn.svm import SVC

# Initiating the classifier
model_svc = SVC()

# Passing the data to classifier
model_svc.fit(X_train_sc, y_train)

# Predictions
y_pred_svc = model_svc.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_svc)*100)

80.03412969283276

In [48]:
svc_report = classification_report(y_test, y_pred_svc)
print(svc_report)

              precision    recall  f1-score   support

          No       0.83      0.92      0.87      1285
         Yes       0.69      0.48      0.56       473

    accuracy                           0.80      1758
   macro avg       0.76      0.70      0.72      1758
weighted avg       0.79      0.80      0.79      1758

#### Logistic Regression Classifier

In [49]:
# Call the Random Forest Classifier
from sklearn.linear_model import LogisticRegression

# Initiating the classifier
model_lr = LogisticRegression()

# Passing the data to classifier
model_lr.fit(X_train_sc, y_train)

# Predictions
y_pred_lr = model_lr.predict(X_test_sc)

# Accuracy Score
print(accuracy_score(y_test,y_pred_lr)*100)

80.31854379977247

In [50]:
lr_report = classification_report(y_test, y_pred_lr)
print(lr_report)

              precision    recall  f1-score   support

          No       0.84      0.91      0.87      1285
         Yes       0.67      0.52      0.59       473

    accuracy                           0.80      1758
   macro avg       0.76      0.72      0.73      1758
weighted avg       0.79      0.80      0.79      1758

### **Ensemble Learning**

#### **Adaboost**

In [51]:
# Call the AdaBoost Classifier
from sklearn.ensemble import AdaBoostClassifier

# Initiating the classifier
model_ada = AdaBoostClassifier(n_estimators=200)

# Passing the data to classifier
model_ada.fit(X_train_sc, y_train)

# Predictions
y_pred_ada = model_ada.predict(X_test_sc)

print("Accuracy of AdaBoost: ", accuracy_score(y_test, y_pred_ada))

Accuracy of AdaBoost:  0.7986348122866894

#### **Gradient Boost**

In [52]:
# Call the GB Classifier
from sklearn.ensemble import GradientBoostingClassifier

# Initiating the classifier
model_gb = GradientBoostingClassifier(n_estimators=200)

# Passing the data to classifier
model_gb.fit(X_train_sc, y_train)

# Predictions
y_pred_gb = model_gb.predict(X_test_sc)

print("Accuracy of GB: ", accuracy_score(y_test, y_pred_gb))

Accuracy of GB:  0.8037542662116041

#### **XG Boost**

In [53]:
y[y=='No'] = 0
y[y=='Yes'] = 1

In [54]:
y

array([0, 0, 1, ..., 0, 1, 0], dtype=object)

In [55]:
# Splitting the data into training & test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

# Converting data to integer
y_test = y_test.astype(int)
y_train = y_train.astype(int)

# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [56]:
# Call the XGB Classifier
from xgboost import XGBClassifier

# Initiating the classifier
model_xgb = XGBClassifier(n_estimators=100, max_depth=4,learning_rate=0.1)

# Passing the data to classifier
model_xgb.fit(X_train_sc, y_train)

# Predictions
y_pred_xgb = model_xgb.predict(X_test_sc)

In [57]:
print("Accuracy of XGB: ", accuracy_score(y_test, y_pred_xgb))

Accuracy of XGB:  0.8060295790671217